### ISSUE TITLE
setting

### ISSUE THREAD

**Issue by vqiangv** [pfZhu/duma_code#2]

**Comment by pfZhu** [comment]
> ### Hello！
> ### I'd like to ask which one you use，albert-xxlarge-v1 or albert-xxlarge-v2
> ### I use the albert-xxlarge-v2 and train model on RTX 3090 (23.70 GiB).
> ### But there is an error . It tells me the cuda out of memory.

We use v2. Maybe you can try smaller batch size/sequence length or a GPU device with larger memory.

**Comment by vqiangv** [comment]
> 

### ok，thanks

**Comment by vqiangv** [comment]
> > ### Hello！
> > ### I'd like to ask which one you use，albert-xxlarge-v1 or albert-xxlarge-v2
> > ### I use the albert-xxlarge-v2 and train model on RTX 3090 (23.70 GiB).
> > ### But there is an error . It tells me the cuda out of memory.
> 
> We use v2. Maybe you can try smaller batch size/sequence length or a GPU device with larger memory.

### I am sorry to bother you again
### Is the albert-base v2?

**Comment by pfZhu** [comment]
> > > ### Hello！
> > > ### I'd like to ask which one you use，albert-xxlarge-v1 or albert-xxlarge-v2
> > > ### I use the albert-xxlarge-v2 and train model on RTX 3090 (23.70 GiB).
> > > ### But there is an error . It tells me the cuda out of memory.
> > 
> > 
> > We use v2. Maybe you can try smaller batch size/sequence length or a GPU device with larger memory.
> 
> ### I am sorry to bother you again
> ### Is the albert-base v2?

all the size including base and xxlarge we use v2. the published version contains more details, please check it on https://ieeexplore.ieee.org/document/9664302

**Comment by vqiangv** [comment]
thank you
